FROM tensorflow/tensorflow:2.11.1-gpu
# tensorflow/tensorflow:2.14.0-gpu Python=3.11 tensorflow==2.14.0 
# tensorflow-addons==0.22.0

RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
    vim \
    build-essential \
    screen \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src

RUN pip install --upgrade pip

# model
RUN pip install --no-cache-dir \
    tensorflow==2.11.1 \
    tensorflow-addons==0.20.0 \
    pandas>=2.1.0 \
    scikit-learn>=1.3.2 \
    Pillow>=10.1.0 \
    tqdm>=4.66.1 \
    seaborn>=0.13.0 \
    torch>=2.2.0 \
    torchvision>=0.17.0 \
    tables>=3.8.0 \
    openTSNE>=1.0.1 \
    jmespath>=1.0.1

# web
RUN pip install --no-cache-dir \
    fastapi>=0.105.0 \
    uvicorn>=0.24 \
    plotly==5.18.0 \
    Jinja2>=3.1.2 \
    python-multipart>=0.0.6 \
    websockets>=12.0 \
    passlib>=1.7.4 \
    python-jose>=3.3.0 \
    email-validator>=2.1.1

# database
RUN pip install --no-cache-dir \
    pymongo>=4.6.1 \
    motor>=3.3.2

CMD ["uvicorn", "web.worker:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
